### ISSUE TITLE
Missing some set up steps

### ISSUE THREAD

**Issue by sganz** [wfcreations/yii2-app-api#3]
Did the install and new to the advanced template but seems that the instructions are missing the -

`php ./init (linux)`

Set up. Also the 
`./yii migrate`

Doesn't work, but not sure if it is supposed to. It currently tosses an exception
`Exception 'yii\base\InvalidConfigException' with message 'The configuration for the "user" component must contain a "class" element.'`
Sandy

**Comment by desenvolvedorindie** [comment]
Thank you
